[workspace]
members = [
    "crates/*",
    "examples/*",
]
resolver = "2"

[workspace.dependencies]
clap = { version = "4", features = ["derive", "env"] }
enventory = { path = "crates/enventory" }
example-lib = { path = "examples/example-lib" }
example-lib-no-macros = { path = "examples/example-lib-no-macros" }
expect-test = "1"
inventory = "0.3"
test-utils = { path = "crates/test-utils" }

[workspace.package]
edition = "2024"
