[package]
name = "example-bin-clap"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
clap = { workspace = true }
enventory = { workspace = true, features = ["clap"] }
example-lib = { workspace = true }
example-lib-no-macros = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }
test-utils = { workspace = true }
