[package]
name = "example-bin"
version = "0.1.0"
edition.workspace = true
publish = false

[[bin]]
name = "example-bin-declarative"
path = "src/declarative.rs"

[[bin]]
name = "example-bin-procedural"
path = "src/procedural.rs"

[dependencies]
clap = { workspace = true }
enventory = { workspace = true, features = ["clap"] }
example-lib = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }
