[package]
name = "example-bin-inventory"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
enventory = { workspace = true, features = ["inventory"] }
example-lib = { workspace = true }
example-lib-no-macros = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }
test-utils = { workspace = true }
